# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('action_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_status', models.IntegerField(blank=True, choices=[(None, 'Rate your progress'), (0, 'Fail'), (5, 'WIP'), (10, 'Success!')], null=True)),
                ('status_logged', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Action')),
            ],
            options={
                'ordering': ['-status_logged'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('goal_achieved', models.BooleanField(default=False)),
                ('actions', models.ManyToManyField(related_name='goals', to='goals.Action')),
                ('categories', models.ManyToManyField(related_name='goals', to='goals.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
