# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
            ],
            options={
                'ordering': ['calculated_at'],
                'get_latest_by': 'calculated_at',
            },
        ),
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_status',
            field=models.IntegerField(blank=True, choices=[(None, 'Take action'), (0, 'Fail'), (5, 'WIP'), (10, 'Success!')], null=True),
        ),
    ]
